name: Generate Datas

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente clicando no botão

# ESSA É A CHAVE MÁGICA QUE FALTAVA: Permissão para a Action salvar o arquivo
permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Gera a animação da cobrinha (versão clara e escura)
      - name: Gerar Snake
        uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: Captain-not-so-obvious
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Faz o push das imagens geradas para a branch 'output'
      - name: Salvar na branch Output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
